name: laminode_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  archive: ^4.0.7
  path: ^1.9.1
  path_provider: ^2.1.5
  json_annotation: ^4.9.0
  file_picker: ^10.3.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  riverpod: ^2.6.1
  go_router: ^17.0.1
  window_manager: ^0.5.1
  lucide_icons: ^0.257.0
  google_fonts: ^7.0.2
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  json_serializable: ^6.11.4
  freezed: ^3.2.4

flutter:
  uses-material-design: true
